function [apo_mu,apo_mass,actual_position_apo,y0_apo, ...
          ica_mu,ica_mass,actual_position_ica,y0_ica, ...
          vz39_mu,vz39_mass,actual_position_vz39,y0_vz39, ...
          rf12_mu,rf12_mass,actual_position_rf12,y0_rf12, ...
          hu4_mu,hu4_mass,actual_position_hu4,y0_hu4, ...
          ff5_mu,ff5_mass,actual_position_ff5,y0_ff5, ...
          a29075_mu,a29075_mass,actual_position_29075,y0_29075, ...
          ft3_mu,ft3_mass,actual_position_ft3,y0_ft3, ...
          fd_mu,fd_mass,actual_position_fd,y0_fd, ...
          t0,tspan] ...
          = set_up     
global corr year
G = 6.67259e-20;   % in km^3/(kg s^2)

% asteroids
mass_ft3 = 5.5*1e10;
mass_fd = 8.3*1e10;
mass_hu4 = 6.2e+05;
mass_ff5 = 7.1e+08;
mass_29075 = 4.4e+12;
mass_rf12 = 5.0e+05;
mass_vz39 = 6.19e6;
mass_ica = 1e12; % in kg
mass_apo = 26.99e9; % in kg
% planets without moons (+ earth)
mass_mer = 0.330104*1e24;
mass_ven = 4.86732*1e24;
mass_ear = 5.97219*1e24;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% moons
mar_moons_mu = 0.0007112+0.0000985;
mar_moons_mass = mar_moons_mu/G;
jup_moons_mu = 5959.916 + 3202.739 + 9887.834 + 7179.289 + 0.138+0.45;
jup_moons_mass = jup_moons_mu/G;
sat_moons_mu = 2.5026 + 7.2027 + 41.2067 + 73.1146 + 153.9426 + ...
               8978.1382 + 0.3727 + 120.5038 + 0.5532 + 0.1263 + 0.0351;
sat_moons_mass = sat_moons_mu/G;
ura_moons_mu = 86.4 + 81.5 + 228.2 + 192.4 + 4.4 + 0.0030 + 0.0036 + ...
               0.0062 + 0.0229 + 0.0119 + 0.0372 + 0.1122 + 0.1931;
ura_moons_mass = ura_moons_mu/G;
nep_moons_mu = 1427.6 + 2.06 + 0.013 + 0.025 + 0.14 + 0.25 + 3.36 + 0.33;
nep_moons_mass = nep_moons_mu/G;
plu_moons_mu = 102.3 + 0.0013 + 0.0065 + 0.0011;
plu_moons_mass = plu_moons_mu/G;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% planets with moons
mass_marbary = 0.641693*1e24 + mar_moons_mass;
mass_jupbary = 1898.13*1e24 + jup_moons_mass;
mass_satbary = 568.319*1e24 + sat_moons_mass;
mass_urabary = 86.8103*1e24 + ura_moons_mass;
mass_nepbary = 102.410*1e24 + nep_moons_mass;
mass_plubary = 0.01309*1e24 + plu_moons_mass;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% asteroids
mu_ft3 = mass_ft3*G;
mu_fd = mass_fd*G;
mu_hu4 = mass_hu4*G;
mu_ff5 = mass_ff5*G;
mu_29075 = mass_29075*G;
mu_rf12 = mass_rf12*G;
mu_vz39 = mass_vz39*G;
% planets without moons (+ earth)
mu_mer = mass_mer*G;
mu_ven = mass_ven*G;
mu_ear = mass_ear*G;
% planets with moons
mu_marbary = mass_marbary*G + mar_moons_mu;
mu_jupbary = mass_jupbary*G + jup_moons_mu;
mu_satbary = mass_satbary*G + sat_moons_mu;
mu_urabary = mass_urabary*G + ura_moons_mu;
mu_nepbary = mass_nepbary*G + nep_moons_mu;
mu_plubary = mass_plubary*G + plu_moons_mu;
% others
mu_moo = 4902.801; % km^3/s^2
mass_moo = mu_moo/G;
mu_apo = mass_apo*G;
mu_cer = 63.2; % km^3/s^2
mass_cer = mu_cer/G;
mu_pal = 14.3;
mass_pal = mu_pal/G;
mu_ves = 17.8;
mass_ves = mu_ves/G;
mu_ica = mass_ica*G;
mu_sun = 1.32712440018*10^11;  % mu_sun (km^3/s^2)
mass_sun = mu_sun/G;

apo_mu = [mu_apo;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
          mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
          mu_moo;mu_plubary];
           
apo_mass = [mass_apo;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
            mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
            mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];    
    
ica_mu = [mu_ica;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
          mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
          mu_moo;mu_plubary];
           
ica_mass = [mass_ica;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
            mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
            mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      

vz39_mu = [mu_vz39;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
           mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
           mu_moo;mu_plubary];
           
vz39_mass = [mass_vz39;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
             mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
             mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      

hu4_mu = [mu_hu4;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
          mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
          mu_moo;mu_plubary];
           
hu4_mass = [mass_hu4;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
            mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
            mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      

ff5_mu = [mu_ff5;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
           mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
           mu_moo;mu_plubary];
           
ff5_mass = [mass_ff5;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
            mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
            mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      
        
a29075_mu = [mu_29075;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
             mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
             mu_moo;mu_plubary];
           
a29075_mass = [mass_29075;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
               mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
               mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      

rf12_mu = [mu_rf12;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
           mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
           mu_moo;mu_plubary];
           
rf12_mass = [mass_rf12;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
             mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
             mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];  
         
ft3_mu = [mu_ft3;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
          mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
          mu_moo;mu_plubary];
           
ft3_mass = [mass_ft3;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
            mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
            mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      
         
fd_mu = [mu_fd;mu_sun;mu_mer;mu_ven;mu_ear;mu_marbary;mu_jupbary;...
         mu_satbary;mu_urabary;mu_nepbary;mu_cer;mu_pal;mu_ves;...
         mu_moo;mu_plubary];
           
fd_mass = [mass_fd;mass_sun;mass_mer;mass_ven;mass_ear;mass_marbary;...
           mass_jupbary;mass_satbary;mass_urabary;mass_nepbary;...
           mass_cer;mass_pal;mass_ves;mass_moo;mass_plubary];      
          
% http://ssd.jpl.nasa.gov/horizons.cgi#top
    load sun
    load mer
    load ven
    load ear
    load marbary
    load jupbary
    load satbary
    load urabary
    load nepbary
    load cer
    load pal
    load ves
    load moo
    load apo
    load plubary
    load ica
    load vz39
    load rf12
    load a29075
    load hu4
    load ff5
    load ft3
    load fd
%     load emb
    
r0_apo = [apo(1,1)...
          apo(1,2)...
          apo(1,3)];
v0_apo = [apo(1,4)...
          apo(1,5)...
          apo(1,6)];
                 
r0_ica = [ica(1,1)...
          ica(1,2)...
          ica(1,3)];
v0_ica = [ica(1,4)...
          ica(1,5)...
          ica(1,6)]; 
      
r0_vz39 = [vz39(1,1)...
           vz39(1,2)...
           vz39(1,3)];
v0_vz39 = [vz39(1,4)...
           vz39(1,5)...
           vz39(1,6)];       

r0_hu4 = [hu4(1,1)...
          hu4(1,2)...
          hu4(1,3)];
v0_hu4 = [hu4(1,4)...
          hu4(1,5)...
          hu4(1,6)];       

r0_ff5 = [ff5(1,1)...
          ff5(1,2)...
          ff5(1,3)];
v0_ff5 = [ff5(1,4)...
          ff5(1,5)...
          ff5(1,6)]; 
       
r0_29075 = [vz39(1,1)...
           vz39(1,2)...
           vz39(1,3)];
v0_29075 = [vz39(1,4)...
           vz39(1,5)...
           vz39(1,6)];       
       
r0_rf12 = [rf12(1,1)...
           rf12(1,2)...
           rf12(1,3)];
v0_rf12 = [rf12(1,4)...
           rf12(1,5)...
           rf12(1,6)]; 
       
r0_ft3 = [ft3(1,1)...
          ft3(1,2)...
          ft3(1,3)];
v0_ft3 = [ft3(1,4)...
          ft3(1,5)...
          ft3(1,6)];       

r0_fd = [fd(1,1)...
         fd(1,2)...
         fd(1,3)];
v0_fd = [fd(1,4)...
         fd(1,5)...
         fd(1,6)];       
       
r0_sun = [sun(1,1)...
          sun(1,2)...
          sun(1,3)];
v0_sun = [sun(1,4)...
          sun(1,5)...
          sun(1,6)];

r0_mer = [mer(1,1)...
          mer(1,2)...
          mer(1,3)];
v0_mer = [mer(1,4)...
          mer(1,5)...
          mer(1,6)];

r0_ven = [ven(1,1)...
          ven(1,2)...
          ven(1,3)];
v0_ven = [ven(1,4)...
          ven(1,5)...
          ven(1,6)];

r0_ear = [ear(1,1)...
          ear(1,2)...
          ear(1,3)];
v0_ear = [ear(1,4)...
          ear(1,5)...
          ear(1,6)];  
      
% r0_emb = [emb(1,1)...
%           emb(1,2)...
%           emb(1,3)];
% v0_emb = [emb(1,4)...
%           emb(1,5)...
%           emb(1,6)];          
                 
r0_marbary = [marbary(1,1)...
              marbary(1,2)...
              marbary(1,3)];
v0_marbary = [marbary(1,4)...
              marbary(1,5)...
              marbary(1,6)];

r0_jupbary = [jupbary(1,1)...
              jupbary(1,2)...
              jupbary(1,3)];
v0_jupbary = [jupbary(1,4)...
              jupbary(1,5)...
              jupbary(1,6)];

r0_satbary = [satbary(1,1)...
              satbary(1,2)...
              satbary(1,3)];
v0_satbary = [satbary(1,4)...
              satbary(1,5)...
              satbary(1,6)];

r0_urabary = [urabary(1,1)...
              urabary(1,2)...
              urabary(1,3)];
v0_urabary = [urabary(1,4)...
              urabary(1,5)...
              urabary(1,6)];
                
r0_nepbary = [nepbary(1,1)...
              nepbary(1,2)...
              nepbary(1,3)];
v0_nepbary = [nepbary(1,4)...
              nepbary(1,5)...
              nepbary(1,6)];

r0_cer = [cer(1,1)...
          cer(1,2)...
          cer(1,3)];
v0_cer = [cer(1,4)...
          cer(1,5)...
          cer(1,6)];

r0_pal = [pal(1,1)...
          pal(1,2)...
          pal(1,3)];
v0_pal = [pal(1,4)...
          pal(1,5)...
          pal(1,6)];
                       
r0_ves = [ves(1,1)...
          ves(1,2)...
          ves(1,3)];
v0_ves = [ves(1,4)...
          ves(1,5)...
          ves(1,6)];
                 
r0_moo = [moo(1,1)...
          moo(1,2)...
          moo(1,3)];
v0_moo = [moo(1,4)...
          moo(1,5)...
          moo(1,6)];  
                 
r0_plubary = [plubary(1,1)...
              plubary(1,2)...
              plubary(1,3)];
v0_plubary = [plubary(1,4)...
              plubary(1,5)...
              plubary(1,6)];                  


y0_apo = [r0_apo ...
          r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
          r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
          r0_moo r0_plubary...
          v0_apo ...
          v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
          v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
          v0_moo v0_plubary]';
  
y0_ica = [r0_ica ...
          r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
          r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
          r0_moo r0_plubary...
          v0_ica ...
          v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
          v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
          v0_moo v0_plubary]';  
      
y0_vz39 = [r0_vz39 ...
           r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
           r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
           r0_moo r0_plubary...
           v0_vz39 ...
           v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
           v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
           v0_moo v0_plubary]';        

y0_hu4 = [r0_hu4 ...
           r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
           r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
           r0_moo r0_plubary...
           v0_hu4 ...
           v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
           v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
           v0_moo v0_plubary]';        
       
y0_rf12 = [r0_rf12 ...
           r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
           r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
           r0_moo r0_plubary...
           v0_rf12 ...
           v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
           v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
           v0_moo v0_plubary]';        

y0_ff5 = [r0_ff5 ...
           r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
           r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
           r0_moo r0_plubary...
           v0_ff5 ...
           v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
           v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
           v0_moo v0_plubary]';        

y0_29075 = [r0_29075 ...
           r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
           r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
           r0_moo r0_plubary...
           v0_29075 ...
           v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
           v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
           v0_moo v0_plubary]';        
       
y0_ft3 = [r0_ft3 ...
          r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
          r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
          r0_moo r0_plubary...
          v0_ft3 ...
          v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
          v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
          v0_moo v0_plubary]';        

y0_fd = [r0_fd ...
         r0_sun r0_mer r0_ven r0_ear r0_marbary r0_jupbary ...
         r0_satbary r0_urabary r0_nepbary r0_cer r0_pal r0_ves ...
         r0_moo r0_plubary...
         v0_fd ...
         v0_sun v0_mer v0_ven v0_ear v0_marbary v0_jupbary ...
         v0_satbary v0_urabary v0_nepbary v0_cer v0_pal v0_ves ...
         v0_moo v0_plubary]';        
       

t0 = 0;

% real data to compare to the numerical results
actual_position_apo = apo(:,1:3);
actual_position_ica = ica(:,1:3);
actual_position_vz39 = vz39(:,1:3);
actual_position_rf12 = rf12(:,1:3);
actual_position_hu4 = hu4(:,1:3);
actual_position_29075 = a29075(:,1:3);
actual_position_ff5 = ff5(:,1:3);
actual_position_ft3 = ft3(:,1:3);
actual_position_fd = fd(:,1:3);

tf = (length(actual_position_ica)-1)*24*60*60;%(23*60*60+56*60+4);
%tf = tf/10; % 1 year instead of 10
tf = tf/year;

steps = length(actual_position_ica); % time step of 1 year
%steps = tf+1;
tspan = linspace(t0,tf,steps);
%tspan = tspan/year;

apo_mu = apo_mu*year^2/corr^3;
ica_mu = ica_mu*year^2/corr^3;
vz39_mu = vz39_mu*year^2/corr^3;
rf12_mu = rf12_mu*year^2/corr^3;
hu4_mu = hu4_mu*year^2/corr^3;
ff5_mu = ff5_mu*year^2/corr^3;
a29075_mu = a29075_mu*year^2/corr^3;
ft3_mu = ft3_mu*year^2/corr^3;
fd_mu = fd_mu*year^2/corr^3;

end 
